#!/usr/bin/env python3
"""Build docs/architecture/diagrams.md from the *.drawio sources.

Run in CI after the render step drops SVGs into an export dir (mirroring the
source tree). For every ``docs/architecture/**/*.drawio`` this:

  1. locates the matching exported SVG(s) — one per page for multi-page files —
     and copies them next to the source so the committed paths are
     deterministic;
  2. computes a read-only diagrams.net viewer URL — the XML is carried in the
     URL fragment, so nothing is uploaded to any server;
  3. writes a Markdown index that renders inline on GitHub (mobile included)
     and links out to the interactive, zoomable viewer.

Usage: python3 build-diagram-index.py [export_dir]   (default: build/diagrams)
The render step is optional — without it the index still emits the viewer
links and marks the inline render as pending. When there are no sources at
all, the index is rewritten to an explicit empty state so a deleted diagram
can't keep exposing a stale render or viewer URL.
"""
from __future__ import annotations

import base64
import glob
import os
import shutil
import sys
import urllib.parse
import zlib

ARCH_DIR = "docs/architecture"
INDEX = os.path.join(ARCH_DIR, "diagrams.md")

HEADER = [
    "<!-- GENERATED by .github/scripts/build-diagram-index.py — do not edit by hand. -->",
    "<!-- The *.drawio files are the source of truth; CI re-renders this on every change. -->",
    "",
    "# Architecture diagrams",
    "",
    "Rendered from the editable `*.drawio` sources in this folder. The SVGs",
    "display inline on GitHub (including the mobile site and app). Tap **Open in",
    "the diagrams.net viewer** for an interactive, zoomable version — the whole",
    "diagram travels in the URL fragment, so nothing is uploaded to any server.",
    "",
]


def deflate_b64(xml: str) -> str:
    # Mirror encodeURIComponent before deflate (see the skill's
    # encode_drawio_url.py) so a literal % or non-ASCII label can't break the
    # browser-side decode.
    pre = urllib.parse.quote(xml, safe="!~*'()")
    c = zlib.compressobj(9, zlib.DEFLATED, -zlib.MAX_WBITS)
    compressed = c.compress(pre.encode("utf-8")) + c.flush()
    return base64.b64encode(compressed).decode("utf-8").replace("\n", "")


def viewer_url(xml: str) -> str:
    return (
        "https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&edit=_blank#R"
        + urllib.parse.quote(deflate_b64(xml), safe="")
    )


def find_svgs(export_dir: str, rel_stem: str) -> list[str]:
    """Exported SVG(s) for a source, one per page. Prefer an exact match on the
    mirrored relative path (avoids collisions between same-named diagrams in
    different folders); fall back to a recursive basename match."""
    # Page 1 is the unsuffixed "<stem>.svg"; rank it first, then page suffixes.
    def page_order(path: str, stem: str) -> tuple[int, str]:
        return (0, "") if os.path.basename(path) == f"{stem}.svg" else (1, path)

    exact = glob.glob(os.path.join(export_dir, f"{glob.escape(rel_stem)}*.svg"))
    if exact:
        return sorted(exact, key=lambda p: page_order(p, os.path.basename(rel_stem)))
    base = os.path.basename(rel_stem)
    matches = glob.glob(
        os.path.join(export_dir, "**", f"{glob.escape(base)}*.svg"), recursive=True
    )
    return sorted(matches, key=lambda p: page_order(p, base))


def title_from_stem(stem: str) -> str:
    return os.path.basename(stem).replace("-", " ").replace("_", " ").title()


def write_index(lines: list[str]) -> None:
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")


def main() -> int:
    export_dir = sys.argv[1] if len(sys.argv) > 1 else "build/diagrams"
    drawios = sorted(
        glob.glob(os.path.join(ARCH_DIR, "**", "*.drawio"), recursive=True)
    )

    if not drawios:
        # No sources: rewrite to an explicit empty state so a removed diagram
        # can't keep exposing an obsolete render or viewer URL.
        write_index(HEADER + ["_No diagrams in this folder yet._"])
        print(f"wrote {INDEX} (no diagrams)")
        return 0

    lines = list(HEADER)
    for d in drawios:
        rel = os.path.relpath(d, ARCH_DIR)  # e.g. "system-architecture.drawio" or "foo/bar.drawio"
        rel_stem = os.path.splitext(rel)[0]  # "system-architecture" or "foo/bar"
        title = title_from_stem(rel_stem)
        with open(d, "r", encoding="utf-8") as f:
            xml = f.read()
        url = viewer_url(xml)

        # Copy each exported page SVG next to its source, preserving subdir.
        embeds: list[str] = []
        for s in find_svgs(export_dir, rel_stem):
            dst_rel = os.path.join(os.path.dirname(rel), os.path.basename(s))
            dst = os.path.join(ARCH_DIR, dst_rel)
            os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
            if os.path.abspath(s) != os.path.abspath(dst):
                shutil.copyfile(s, dst)
            embeds.append(dst_rel.replace(os.sep, "/"))

        lines.append(f"## {title}")
        lines.append("")
        if embeds:
            for e in embeds:
                lines.append(f"![{title}]({e})")
                lines.append("")
        else:
            lines.append(
                f"_Inline render pending the next CI run — open "
                f"[`{rel}`]({rel}) in draw.io, or use the viewer link below._"
            )
            lines.append("")
        lines.append(f"- [Open in the diagrams.net viewer]({url})")
        lines.append(f"- Source: [`{rel}`]({rel})")
        lines.append("")

    write_index(lines)
    print(f"wrote {INDEX} for {len(drawios)} diagram(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
