#!/usr/bin/env python3
"""Build docs/architecture/diagrams.md from the *.drawio sources.

Run in CI after the drawio export step drops SVGs into an export dir. For each
``docs/architecture/*.drawio`` this:

  1. locates the matching exported SVG (by filename stem) and copies it next to
     the source as ``<stem>.svg`` so the committed path is deterministic,
     regardless of how the exporter nests / page-suffixes its output;
  2. computes a read-only diagrams.net viewer URL — the XML is carried in the
     URL fragment, so nothing is uploaded to any server;
  3. writes a Markdown index that renders inline on GitHub (mobile included)
     and links out to the interactive, zoomable viewer.

Usage: python3 build-diagram-index.py [export_dir]   (default: build/diagrams)
The SVG step is optional — without it the index still emits the viewer links
and marks the inline render as pending.
"""
from __future__ import annotations

import base64
import glob
import os
import shutil
import sys
import urllib.parse
import zlib

ARCH_DIR = "docs/architecture"
INDEX = os.path.join(ARCH_DIR, "diagrams.md")


def deflate_b64(xml: str) -> str:
    # Mirror encodeURIComponent before deflate (see the skill's
    # encode_drawio_url.py) so a literal % or non-ASCII label can't break the
    # browser-side decode.
    pre = urllib.parse.quote(xml, safe="!~*'()")
    c = zlib.compressobj(9, zlib.DEFLATED, -zlib.MAX_WBITS)
    compressed = c.compress(pre.encode("utf-8")) + c.flush()
    return base64.b64encode(compressed).decode("utf-8").replace("\n", "")


def viewer_url(xml: str) -> str:
    return (
        "https://viewer.diagrams.net/?tags=%7B%7D&lightbox=1&edit=_blank#R"
        + urllib.parse.quote(deflate_b64(xml), safe="")
    )


def find_svg(export_dir: str, stem: str) -> str | None:
    matches = sorted(
        glob.glob(os.path.join(export_dir, "**", f"{stem}*.svg"), recursive=True)
    )
    for m in matches:  # prefer an exact <stem>.svg over a page-suffixed name
        if os.path.splitext(os.path.basename(m))[0] == stem:
            return m
    return matches[0] if matches else None


def title_from_stem(stem: str) -> str:
    return stem.replace("-", " ").replace("_", " ").title()


def main() -> int:
    export_dir = sys.argv[1] if len(sys.argv) > 1 else "build/diagrams"
    drawios = sorted(glob.glob(os.path.join(ARCH_DIR, "*.drawio")))
    if not drawios:
        print(f"no .drawio files under {ARCH_DIR}")
        return 0

    lines = [
        "<!-- GENERATED by .github/scripts/build-diagram-index.py — do not edit by hand. -->",
        "<!-- The *.drawio files are the source of truth; CI re-renders this on every change. -->",
        "",
        "# Architecture diagrams",
        "",
        "Rendered from the editable `*.drawio` sources in this folder. The SVGs",
        "display inline on GitHub (including the mobile site and app). Tap **Open in",
        "the diagrams.net viewer** for an interactive, zoomable version — the whole",
        "diagram travels in the URL fragment, so nothing is uploaded to any server.",
        "",
    ]

    for d in drawios:
        stem = os.path.splitext(os.path.basename(d))[0]
        title = title_from_stem(stem)
        with open(d, "r", encoding="utf-8") as f:
            xml = f.read()
        url = viewer_url(xml)

        svg_rel = f"{stem}.svg"
        svg_dst = os.path.join(ARCH_DIR, svg_rel)
        src = find_svg(export_dir, stem)
        if src and os.path.abspath(src) != os.path.abspath(svg_dst):
            shutil.copyfile(src, svg_dst)

        lines.append(f"## {title}")
        lines.append("")
        if os.path.exists(svg_dst):
            lines.append(f"![{title}]({svg_rel})")
        else:
            lines.append(
                f"_Inline render pending the next CI run — open "
                f"[`{os.path.basename(d)}`]({os.path.basename(d)}) in draw.io, "
                f"or use the viewer link below._"
            )
        lines.append("")
        lines.append(f"- [Open in the diagrams.net viewer]({url})")
        lines.append(f"- Source: [`{os.path.basename(d)}`]({os.path.basename(d)})")
        lines.append("")

    with open(INDEX, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print(f"wrote {INDEX} for {len(drawios)} diagram(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
